name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lilypond-version: [2.22.1]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install LilyPond
      run: |
        wget --no-verbose https://lilypond.org/download/binaries/linux-64/lilypond-${{ matrix.lilypond-version }}-1.linux-64.sh
        sudo sh lilypond-${{ matrix.lilypond-version }}-1.linux-64.sh --batch
    - name: Clone lilypond-bend-spanner
      run: git clone https://github.com/nwhetsell/lilypond-bend-spanner.git
    - name: Run tests
      run: lilypond test.ly

    - name: Archive
      uses: actions/upload-artifact@main
      with:
        name: ${{ runner.os }} artifacts
        path: test.pdf
        if-no-files-found: error
