name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lilypond-version: [2.24.0]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install LilyPond
      run: |
        wget --no-verbose https://gitlab.com/lilypond/lilypond/-/releases/v2.24.0/downloads/lilypond-2.24.0-linux-x86_64.tar.gz
        tar -xf lilypond-2.24.0-linux-x86_64.tar.gz
        echo "$(pwd)/lilypond-2.24.0/bin" >> $GITHUB_PATH
    - name: Run tests
      run: lilypond test.ly

    - name: Archive
      uses: actions/upload-artifact@main
      with:
        name: ${{ runner.os }} artifacts
        path: test.pdf
        if-no-files-found: error
